#!/bin/bash
# Butch Benson

cat << EOF
A gruff looking man, Butch Benson was only hired on a couple years ago. His sleeves have blood stains on them, and you can't tell if they're old or fresh, but surely just from working with raw meat for meals, right?
EOF

talking=0
while [ $talking -eq 0 ]
do
# Random prompts
rand=$(( RANDOM % 2 ))
case $rand in 
	0) echo "Hmph, what is it?"
	;;
	1) echo "What?"
	;;
	2) echo "You got something to say to me?"
	;;
	*) echo "Go on, move it!"
	;;

esac

cat << EOF	

                        Please Select:

                        1. What did you think of Sir Walter Oswald?
                        2. Where were you at the time of the murder?
			3. Anything else you want to note?
                        0. (Stop Talking)
EOF

read -p "Enter selection [0-3] > " selection

# act on selection
case $selection in
        1) echo "That arsehole? Nothing good that's for sure. He's always late on my paycheck, and for a rich guy, you'd think he'd have the dough to pay his own staff. Not to mention this cramped kitchen they have me slaving away in all the time. It doesn't even have proper ventilation!"
        ;;
        2) echo "Making dinner! What do you think? That dinner was a nightmare to make. It took ages in the oven!"
        ;;
	3) echo "Now don't let this get around, but that stupid gardener doesn't even do half the work I do, and still gets paid on time. He's always complaining about how his garden's are getting ruined too, but who cares! I suppose he might have a little bit of a grudge against ol' Oswald for ruining the 'pretty flowers' with his golf buddies"
	;;
        0) talking=1
	 break
        ;;
        *) echo "Invalid entry."
        ;;
esac
done
