#!/bin/bash
# Mildred Mannington

cat << EOF
Mildred Mannington seems to be a very prim and proper maid by societies standards. On her apron, you can see a powdery gray substance. Dust, maybe chalk of some kind. She seems a little extra stiff and tense when you approach. Could she be hiding something?
EOF

talking=0
while [ $talking -eq 0 ]
do
# Random prompts
rand=$(( RANDOM % 2 ))
case $rand in 
	0) echo "Detective. What can I help you with."
	;;
	1) echo "Good evening Detective."
	;;
	2) echo "What would you like to know?"
	;;
	*) echo "Hello Detective."
	;;

esac

cat << EOF	

                        Please Select:

                        1. What did you think of Sir Walter Oswald?
                        2. Where were you at the time of the murder?
			3. Anything else you want to note?
                        0. (Stop Talking)
EOF

read -p "Enter selection [0-3] > " selection

# act on selection
case $selection in
        1) echo "Why do you ask? Oh, right. Um, He was a wonderful boss. I was very happy to work for him. I am very sad that he has passed..."
        ;;
        2) echo "I was cleaning the parlor. Mary came in later in the evening to rest on the couch, so I tried to hurry to clean up and get out of her way."
        ;;
	3) echo "Mrs. Oswald has always been out to get me. Every since... never mind. Forget I said anything!! Please don't tell her I said anything!"
	;;
        0) talking=1
	 break
        ;;
        *) echo "Invalid entry."
        ;;
esac
done
