#!/bin/bash
# John Oswald

cat << EOF

The eldest of the Oswald children. He seems like a very stressed out young man, with his eyes darting everywhere. You think you can remember his name from the local newspaper that you read recently. Something about him winning a math competition in the same weekend as a huge football game.

EOF

talking=0
while [ $talking -eq 0 ]
do
# Random prompts
rand=$(( RANDOM % 3 ))
case $rand in 
	0) echo "\nHuh? oh hi. What can do for you?\n"
	;;
	1) echo "\nShoot, didn't see you there Detective!\n"
	;;
	2) echo "\nHello! If there's anything I can do to help, let me know.\n"
	;;
	*) echo "\n(John bolts to attention) Detective! What can I do to help?\n"
	;;

esac

cat << EOF	

                        Please Select:

                        1. What did you think of Sir Walter Oswald?
                        2. Where were you at the time of the murder?
			3. Anything else you want to note?
                        0. (Stop Talking)

EOF

read -p "Enter selection [0-3] > " selection

# act on selection
case $selection in
        1) echo -e "\nOh, my dad. Yeah, he's cool and all. Always wants what's best for me. He pushes me pretty hard, but I know he and mom are doing it to make me the best I can be, right?\n"
        ;;
        2) echo -e "\nI was just playing a little billiards. I know I should be studying or training, heck, even working on my college applications, my mom will not get off my back about that! But I just don't know what I even want to do after high school, let alone what major to go into or college to choose...\n"
        ;;
	3) echo -e "\nIf anyone did it, I bet it was Alex, they're always sulking around. And of course mom and dad are never pushing them to be the best they can be. Alex is always just being lazy and reading books all day.\n"
	;;
        0) talking=1
	 break
        ;;
        *) echo -e "\nInvalid entry.\n"
        ;;
esac
done
