#!bin/bash






# Sir Walter Oswald's second child.
# Mary seems to be a shy and polite young woman, but very nervous. Of course, this might be expected,
# seeing as how her father has just been murdered.
#
#
#
#
#
#
#
